name: 'Publish to Apps@QB'
description: 'Publishing to apps.quickbirdstudios.com'
inputs:
  token:
    description: 'Upload Key'
    required: true
    type: string
  file:
    description: 'The file (IPA or APK) to upload'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        response_code=$(curl 'https://apps.quickbirdstudios.com/apps/29/releases/' \
          --form 'upload_key="${{ inputs.token }}"' \
          --form 'release[branch]=${{ github.ref_name }}' \
          --form 'release[commit]=${{ github.sha }}' \
          --form 'release[build]=@${{ inputs.file }}' \
          -w "\n%{http_code}")

        if [[ $response_code -ge 400 ]]; then 
            echo "Upload failed with $response_code"
            exit 1
        fi