name: Sanity Requirements

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  sanity:
    uses: QuickBirdEng/workflows/.github/workflows/sanity-requirements.yml@main
    with:
      ticket-prefixes: "MNET"
    secrets: inherit
