name: Sanity Requirements

on:
  push:
    branches:
      - "**"
      - "!main"
      - "!develop"
      - "!release/*"
  workflow_dispatch:

jobs:
  sanity:
    uses: QuickBirdEng/workflows/.github/workflows/sanity-requirements.yml@codex/extract-sanity-requirements
    with:
      ticket-prefixes: "MNET"
    secrets: inherit
