name: Release Workflow

on:
  workflow_call:
    inputs:
      git-lfs:
        description: "Checkout the project with git lfs"
        type: boolean
        default: false
  workflow_dispatch:

env:
  ENVIRONMENT_FILE: .env

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-build-number:
    runs-on: [self-hosted]
    outputs:
      build-number: ${{ steps.build-number-generator.outputs.build-number }}
    steps:
      - name: Generate Build Number
        id: build-number-generator
        run: |
          build_number=$(date +%s)
          echo "build-number=$build_number" >> $GITHUB_OUTPUT
          echo "Build Number: $build_number"

  branch:
    needs: [generate-build-number]
    uses: ./.github/workflows/android-common-with-lint.yml
    with:
      build-number: ${{ needs.generate-build-number.outputs.build-number }}
    secrets: inherit

  android-bundle:
      runs-on: [self-hosted, Linux]
      needs: [generate-build-number, branch]
      steps:
        - uses: actions/checkout@v3
          with:
            lfs: ${{ inputs.git-lfs }}
        - run: echo "BuildForRelease=true" >> $GITHUB_ENV
        - uses: QuickBirdEng/actions/setup-version@v1.1
          with:
            build-number: ${{ needs.generate-build-number.outputs.build-number }}
        - uses: QuickBirdEng/actions/setup-android@v1.1
          with:
            key-store-file-content: ${{ secrets.ANDROID_KEYSTORE_FILE_CONTENT }}
            key-store-password: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
            signing-key-alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
            signing-key-password: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
        - name: Generate Bundle (.aab)
          shell: bash
          run: ./gradlew bundleRelease
        - name: Compress & Upload Artifact to QB Spaces
          uses: QuickBirdEng/actions/compress-and-upload-artifact-qb@v1.1
          with:
            access-key: ${{ secrets.DO_ACCESS_KEY }}
            secret-key: ${{ secrets.DO_SECRET_KEY }}
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            name-suffix: android
            artifact-path: app/build/outputs/bundle/release/app-release.aab
