name: Android Branch Workflow
env:
  ENVIRONMENT_FILE: .env

on:
  workflow_call:
    inputs:
      build-number:
        description: 'Build Number'
        type: string
        required: false
      git-lfs:
        description: "Checkout the project with git lfs"
        type: boolean
        default: false
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: ${{ inputs.git-lfs }}
      - uses: QuickBirdEng/actions/setup-android-for-build@v1
      - run: ./gradlew quickLint
  unitTests:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: ${{ inputs.git-lfs }}
      - uses: QuickBirdEng/actions/setup-android-for-build@v1
      - run: ./gradlew test
  androidTests:
    runs-on: [self-hosted, Linux, android]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: ${{ inputs.git-lfs }}
      - uses: QuickBirdEng/actions/setup-android-for-build@v1
      - run: ./gradlew cAT --stacktrace
  android-build:
    runs-on: [self-hosted, Linux]
    needs: [lint, unitTests, androidTests]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: ${{ inputs.git-lfs }}
      - run: echo "BuildForRelease=true" >> $GITHUB_ENV
      - uses: QuickBirdEng/actions/setup-version@v1
        with:
          build-number: ${{ inputs.build-number }}
      - uses: QuickBirdEng/actions/setup-android@v1
        with:
          key-store-file-content: ${{ secrets.ANDROID_KEYSTORE_FILE_CONTENT }}
          key-store-password: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          signing-key-alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          signing-key-password: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
      - name: Generate APK
        shell: bash
        run: ./gradlew assembleRelease
