name: Release Workflow

on:
  workflow_call:
  workflow_dispatch:

env:
  ENVIRONMENT_FILE: .env

jobs:
  generate-build-number:
    runs-on: [self-hosted]
    outputs:
      build-number: ${{ steps.build-number-generator.outputs.build-number }}
    steps:
      - name: Generate Build Number
        id: build-number-generator
        run: | 
          build_number=$(date +%s)
          echo "build-number=$build_number" >> $GITHUB_OUTPUT
          echo "Build Number: $build_number"

  branch:
    needs: [generate-build-number]
    uses: QuickBirdEng/workflows/.github/workflows/android-common.yml@main
    with:
      build-number: ${{ needs.generate-build-number.outputs.build-number }}
    secrets: inherit

  android-bundle:
    runs-on: [self-hosted, Linux]
    needs: [generate-build-number, branch]
    steps:
      - uses: actions/checkout@v3
      - run: echo "BuildForRelease=true" >> $GITHUB_ENV
      - uses: QuickBirdEng/actions/setup-version@main
        with:
          build-number: ${{ needs.generate-build-number.outputs.build-number }}
      - uses: QuickBirdEng/actions/setup-android@main
        with:
          key-store-file-content: ${{ secrets.ANDROID_KEYSTORE_FILE_CONTENT }}
          key-store-password: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          signing-key-alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          signing-key-password: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
      - name: Setup API Key (if secret is set)
        shell: bash
        run: |
          if [[ '${{ secrets.RAW_API_KEY }}' != '' ]]; then
            echo "RAW_API_KEY=${{ secrets.RAW_API_KEY }}" >> .env.credentials
          fi
      - name: Generate Bundle (.aab)
        shell: bash
        run: ./gradlew bundleRelease
      - name: Compress & Upload Artifact to QB Spaces
        uses: QuickBirdEng/actions/compress-and-upload-artifact-qb@main
        with:
          access-key: ${{ secrets.DO_ACCESS_KEY }}
          secret-key: ${{ secrets.DO_SECRET_KEY }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          name-suffix: android
          artifact-path: app/build/outputs/bundle/release/app-release.aab