on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ inputs.name }}
