on:
  workflow_call:
    inputs:
      flutter-version:
        required: true
        type: string
      relative-include-path:
        required: false
        type: string
      relative-exclude-path:
        required: false
        type: string
      git-lfs:
        description: "Checkout the project with git lfs"
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  secret_scanner:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: ${{ inputs.git-lfs }}
      - run: echo ${{inputs.relative-include-path}} ${{inputs.relative-exclude-path}}
      - uses: max/secret-scan@master
        with:
          include_path: '${{ inputs.relative-include-path }}'
          exclude_path: '${{ inputs.relative-exclude-path }}'
#      - run: echo >\n
#          !!!!!!!!!!!!!! Message from the security officer !!!!!!!!!!!!!!\n
#          Should there be findings, think about if that upload-key should be put into source code?\n
#          \n
#          If the upload-key can be in the source code, put the path of that file into a text file and provide that path as an input parameter for the security checks job \"relative-exclude-path":" .pathtofile/secret_check_ignore_paths.txt\"\n
#          If the upload-key should not be in the source code, consider putting it into the GitHub secrets\n

  trufflehog-package-analysis:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set env variables for check
        if: inputs.relative-exclude-path != ''
        run: |
          echo 'TH_EXCLUDE_PATHS=--exclude-paths=${{ inputs.relative-exclude-path }}' >> $GITHUB_ENV
      - name: set env variables for check
        if: inputs.relative-include-path != ''
        run: |
          echo 'TH_INCLUDE_PATHS=--include-paths=${{ inputs.relative-include-path }}' >> $GITHUB_ENV
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified ${{ env.TH_EXCLUDE_PATHS }} ${{ env.TH_INCLUDE_PATHS }}

  # https://github.com/fundacaocerti/mobsf-action
  # https://github.com/fundacaocerti/mobsf-action/pull/16
  # https://github.com/fundacaocerti/mobsf-action/pull/17
#  mobsf_scan_only:
#    runs-on: [ self-hosted ]
#    steps:
#      - name: Checkout Repo
#        uses: actions/checkout@master
#      - name: Set-up Java
#        uses: actions/setup-java@v1
#        with:
#          java-version: '12.x'
#      - name: Set-up Flutter
#        uses: subosito/flutter-action@v1
#        with:
#          flutter-version: ${{ inputs.flutterVersion }}
#      - name: Flutter Install Dependencies
#        run: flutter pub get
#      - name: Flutter Build
#        run: flutter build apk
##      - name: Fix Permissions for MobSF Docker
##        run: |
##          set -e
##          sudo mkdir -p /home/runner/work/_temp/_github_home
##          sudo chown -R 9901:9901 /home/runner/work/_temp/_github_home
##          sudo mkdir -p /home/runner/work/$REPO_NAME/$REPO_NAME
##          sudo chown -R 9901:9901 /home/runner/work/$REPO_NAME/$REPO_NAME
##        env:
##          REPO_NAME: ${{ github.event.repository.name }}
#      - name: Run MobSF Analysis
#        uses: fundacaocerti/mobsf-action@v1.7.2
#        env:
#          INPUT_FILE_NAME: build/app/outputs/apk/app.apk
#          SCAN_TYPE: apk
#          OUTPUT_FILE_NAME: mobsf-report
##      - name: Cleanup MobSF Permissions
##        run: |
##          set -e
##          sudo chown -R runner:docker /home/runner/work/_temp/_github_home
##          sudo chown -R runner:docker /home/runner/work/$REPO_NAME/$REPO_NAME
##        env:
##          REPO_NAME: ${{ github.event.repository.name }}
#      - name: Upload MobSF Analysis PDF Result
#        uses: actions/upload-artifact@v2
#        with:
#          name: mobsf-report-apk.pdf
#          path: mobsf-report-apk.pdf
#      - name: Upload MobSF Analysis JSON Result
#        uses: actions/upload-artifact@v2
#        with:
#          name: mobsf-report-apk.json
#          path: mobsf-report-apk.json

#  mobsf_scan_ios:
#    runs-on: [ self-hosted, ios ]
#    steps:
#      - name: Checkout Repo
#        uses: actions/checkout@master
#      - name: Set-up Java
#        uses: actions/setup-java@v1
#        with:
#          java-version: '12.x'
#      - name: Set-up Flutter
#        uses: subosito/flutter-action@v1
#        with:
#          flutter-version: ${{ inputs.flutterVersion }}
#      - name: Flutter Install Dependencies
#        run: flutter pub get
#      - name: Flutter Build
#        run: flutter build ipa
#      - name: Run MobSF Analysis
#        uses: fundacaocerti/mobsf-action@v1.7.2
#        env:
#          INPUT_FILE_NAME: build/ios/archive/Runner.xcarchive
#          SCAN_TYPE: ipa
#          OUTPUT_FILE_NAME: mobsf-report
#      - name: Upload MobSF Analysis PDF Result
#        uses: actions/upload-artifact@v2
#        with:
#          name: mobsf-report-ipa.pdf
#          path: mobsf-report-ipa.pdf
#      - name: Upload MobSF Analysis JSON Result
#        uses: actions/upload-artifact@v2
#        with:
#          name: mobsf-report-ipa.json
#          path: mobsf-report-ipa.json
