on:
  workflow_call:
    inputs:
      flutter-version:
        required: true
        type: string
      relative-include-path:
        required: false
        type: string
      relative-exclude-path:
        required: false
        type: string
      git-lfs:
        description: "Checkout the project with git lfs"
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  secret_scanner:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: ${{ inputs.git-lfs }}
      - run: echo ${{inputs.relative-include-path}} ${{inputs.relative-exclude-path}}
      - uses: max/secret-scan@master
        with:
          include_path: '${{ inputs.relative-include-path }}'
          exclude_path: '${{ inputs.relative-exclude-path }}'
#      - run: echo >\n
#          !!!!!!!!!!!!!! Message from the security officer !!!!!!!!!!!!!!\n
#          Should there be findings, think about if that upload-key should be put into source code?\n
#          \n
#          If the upload-key can be in the source code, put the path of that file into a text file and provide that path as an input parameter for the security checks job \"relative-exclude-path":" .pathtofile/secret_check_ignore_paths.txt\"\n
#          If the upload-key should not be in the source code, consider putting it into the GitHub secrets\n

  trufflehog-package-analysis:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set env variables for check
        if: inputs.relative-exclude-path != ''
        run: |
          echo 'TH_EXCLUDE_PATHS=--exclude-paths=${{ inputs.relative-exclude-path }}' >> $GITHUB_ENV
      - name: set env variables for check
        if: inputs.relative-include-path != ''
        run: |
          echo 'TH_INCLUDE_PATHS=--include-paths=${{ inputs.relative-include-path }}' >> $GITHUB_ENV
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified ${{ env.TH_EXCLUDE_PATHS }} ${{ env.TH_INCLUDE_PATHS }}

