name: Flutter Manual Deploy Workflow
env:
  ENVIRONMENT_FILE: .env

on:
  workflow_call:
    inputs:
      ios-build-arguments:
        description: "any extra arguments such as using sksl or passing a variable using --dart-define etc. for iOS build"
        type: string
        required: false
      android-build-arguments:
        description: "any extra arguments such as using sksl or passing a variable using --dart-define etc. for Android build"
        type: string
        required: false
      publish-to-testflight:
        description: "Should publish to Testflight?"
        type: boolean
        default: false
      working-directory:
        description: "the directory to run each job of the workflow in"
        type: string
        default: "."
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-build-number:
    runs-on: [self-hosted]
    outputs:
      build-number: ${{ steps.build-number-generator.outputs.build-number }}
    steps:
      - name: Generate Build Number
        id: build-number-generator
        run: |
          build_number=$(date +%s)
          echo "build-number=$build_number" >> $GITHUB_OUTPUT
          echo "Build Number: $build_number"

  ios-publish:
    runs-on: [self-hosted, macOS]
    needs: [generate-build-number]
    steps:
      - uses: QuickBirdEng/actions/checkout-ssh@main
        with:
          ssh-private-key: ${{ secrets.CI_SSH_PRIVATE_KEY_FOR_GITHUB_PRIVATE_REPOS }}
      - uses: QuickBirdEng/actions/setup-ios@main
      - uses: QuickBirdEng/actions/flutter-build@main
        id: build
        with:
          build-type: ipa
          build-number: ${{ needs.generate-build-number.outputs.build-number }}
          build-arguments: --no-codesign ${{ inputs.ios-build-arguments }}
          clean: true
          working-directory: ${{ inputs.working-directory }}
      - uses: QuickBirdEng/actions/upload-debug-symbols-to-sentry@main
        env:
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        if: ${{ env.SENTRY_PROJECT != '' }}
        with:
          url: ${{ secrets.SENTRY_URL }}
          organization: ${{ secrets.SENTRY_ORG }}
          project: ${{ secrets.SENTRY_PROJECT }}
          auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          xc-archive-path: ${{ steps.build.outputs.artifact-path }}
        continue-on-error: true
