name: Flutter Branch Workflow
env:
  ENVIRONMENT-FILE: .github/.env

on:
  workflow_call:
    inputs:
      ssh-private-key:
        required: true
      qbs-maven-username:
        default: ""
      qbs-maven-password:
        default: ""
      ios-build-arguments:
        description: 'any extra arguments such as using sksl or passing a variable using --dart-define etc. for iOS build'
        required: false
      android-build-arguments:
        description: 'any extra arguments such as using sksl or passing a variable using --dart-define etc. for Android build'
        required: false
      upload-key:
        description: 'Upload Key for apps.quickbirdstudios.com'
        required: true
      publish-to-testflight:
        description: 'Should publish to Testflight?'
        default: false
      match-password:
        description: 'Password for Match Repo'
        required: true
      apple-auth-key-id:
        description: 'Auth Key'
        required: true
      apple-auth-key-issuer-id:
        description: 'Auth Key Issuer ID'
        required: true
      apple-auth-key-content:
        description: 'Auth Key Content'
        required: true
      apple-auth-key-encoding:
        description: 'Auth Key Encoding'
        required: true

    workflow_dispatch:
      
jobs:
  branch:
    uses: QuickBirdEng/workflows/.github/workflows/flutter-release.yml@feature/shared-workflows-flutter
    with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
        qbs-maven-username: ${{ inputs.qbs-maven-username }}
        qbs-maven-password: ${{ inputs.qbs-maven-password }}
        ios-build-arguments: ${{ inputs.ios-build-arguments }}
        android-build-arguments: ${{ inputs.android-build-arguments }}
        upload-key: ${{ inputs.upload-key }}
        publish-to-testflight: ${{ inputs.publish-to-testflight }}
        match-password:  ${{ inputs.match-password }}
        apple-auth-key-id: ${{ inputs.apple-auth-key-id }}
        apple-auth-key-issuer-id: ${{ inputs.apple-auth-key-issuer-id }}
        apple-auth-key-content: ${{ inputs.apple-auth-key-content }}
        apple-auth-key-encoding: ${{ inputs.apple-auth-key-encoding }}

  android-bundle:
      runs-on: [self-hosted]
      needs: [branch]
      steps:
        - uses: actions/checkout@v3
        - uses: webfactory/ssh-agent@v0.6.0
          with:
            ssh-private-key: ${{ secrets.CI-SSH-PRIVATE-KEY-FOR-GITHUB-PRIVATE-REPOS }}
        - uses: ./actions/setup-android
          with:
            qbsMavenUsername: ${{ inputs.qbs-maven-username }}
            qbsMavenPassword: ${{ inputs.qbs-maven-password }}
        - uses: ./actions/flutter-build
          id: flutter-build
          with:
            clean: true
            build-type: appbundle
            build-number: ${{ needs.generate-build-number.outputs.build-number }}
            build-arguments: ${{ inputs.android-build-arguments }}
        # - name: 'Upload AppBundle as artifact'
        #   uses: actions/upload-artifact@v3
        #   with:
        #    name: app-bundle
        #    path: ${{ steps.flutter-build.outputs.artifact-path }}