name: iOS Certificates and Provisioning Profiles Management Workflow
env:
  ENVIRONMENT_FILE: .env

on:
  workflow_call:
    inputs:
      platform:
        description: 'flutter or ios?'
        type: string
        default: 'ios'
      certificate-type:
        description: 'Possible values are development, distribution, or both'
        type: string
        default: development
      delete-certificates-from-repo:
        description: 'Set to true only if the certificates have expired'
        type: boolean
        default: false
      working-directory:
        description: 'Provide working directory (if you are not using default directory structure)'
        type: string
        default: '.'
      git-lfs:
        description: "Checkout the project with git lfs"
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  renew:
    runs-on: [self-hosted, macOS]
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    if: contains('["nasirky","acpoppe","grafele"]', github.triggering_actor)
    steps:
      - uses: QuickBirdEng/actions/checkout-ssh@main
        with:
          ssh-private-key: ${{ secrets.CI_SSH_PRIVATE_KEY_FOR_GITHUB_PRIVATE_REPOS }}
          git-lfs: ${{ inputs.git-lfs }}
      - uses: QuickBirdEng/actions/setup-environment@main
      - run: git clone -b main --single-branch ${{ secrets.MATCH_REPO }}
      - name: Remove Certificates
        if: inputs.delete-certificates-from-repo
        run: |
          repo_name=$(basename ${{secrets.MATCH_REPO }}) && repo_name=${repo_name/.git/}
          if [[ -d $repo_name/certs ]]; then
            cd $repo_name/certs
            [[ '${{ inputs.certificate-type }}' == 'distribution' ]] && rm -rf distribution || rm -rf development
          fi
      - name: Remove existing profiles from match repository
        run: |
          repo_name=$(basename ${{secrets.MATCH_REPO }}) && repo_name=${repo_name/.git/}
          cd $repo_name

          if [[ ${{ env.BUNDLE_ID }} == '' ]]; then
            echo "BUNDLE_ID is not set. Please set it in the .env file"
            exit 1;
          fi

          if [[ '${{ inputs.certificate-type }}' == 'distribution' ]]; then
            rm -f profiles/adhoc/*${{ env.BUNDLE_ID }}*
            rm -f profiles/appstore/*${{ env.BUNDLE_ID }}*
          else
             rm -f profiles/development/*${{ env.BUNDLE_ID }}*
          fi

          git remote add match ${{ secrets.MATCH_REPO }}
          git add . && git commit -m "Remove ${{ inputs.certificate-type }} profiles and (optionally) certificates for ${{ env.BUNDLE_ID }}" && git push match || true
      - uses: QuickBirdEng/actions/setup-fastlane@main
        with:
          platform: ${{ inputs.platform }}
          working-directory: ${{ inputs.working-directory }}
      - uses: QuickBirdEng/actions/setup-fastlane-environment@main
        with:
          match-repository: ${{ secrets.MATCH_REPO }}
          match-password: ${{ secrets.MATCH_PASSWORD }}
          match-apple-id: ${{ secrets.APPLE_ID }}
          match-apple-team-id: ${{ secrets.APPLE_TEAM_ID }}
          apple-auth-key-id: ${{ secrets.APPLE_AUTH_KEY_ID }}
          apple-auth-key-issuer-id: ${{ secrets.APPLE_AUTH_KEY_ISSUER_ID }}
          apple-auth-key-content: ${{ secrets.APPLE_AUTH_KEY_CONTENT }}
          apple-auth-key-encoding: "base64"
      - name: Generate/Download provisioning profiles & (maybe) certificates
        shell: bash -l {0}
        run: |
            [[ "${{ inputs.platform }}" == "flutter" ]] && cd ios

            if [[ '${{ inputs.certificate-type }}' == 'distribution' || '${{ inputs.certificate-type }}' == 'both' ]]; then
              bundle exec fastlane match_for_signing type:appstore refresh_certificates:true
              bundle exec fastlane match_for_signing type:adhoc refresh_certificates:true
            fi
            if [[ '${{ inputs.certificate-type }}' == 'development' || '${{ inputs.certificate-type }}' == 'both' ]]; then
              bundle exec fastlane match_for_signing type:development refresh_certificates:true
            fi
