name: K8s Add Docker Credentials

on:
  workflow_call:
    inputs:
      namespace:
        description: "Namespace"
        type: string
        required: true
      git-lfs:
        description: "Checkout the project with git lfs"
        type: boolean
        default: false
  workflow_dispatch:

jobs:
  deploy-dns-utils:
    runs-on: [self-hosted, docker]
    if: contains('["acpoppe","KlausNie","kupeliorhun", "nasirky"]', github.triggering_actor)
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: ${{ inputs.git-lfs }}
      - uses: azure/setup-kubectl@v3
      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          context: ${{ secrets.KUBE_CONTEXT }}
      - run: kubectl create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=${{ secrets.DOCKER_HUB_USER }} --docker-password=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} -n ${{ inputs.namespace }}
