name: SOUP - CVE Check for Packages

on:
  workflow_call:

jobs:
  reports:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: QuickBirdEng/actions/checkout-ssh@main
        with:
          ssh-private-key: ${{ secrets.CI_SSH_PRIVATE_KEY_FOR_GITHUB_PRIVATE_REPOS }}
      - name: Copy scripts
        shell: bash
        run: git clone git@github.com:QuickBirdEng/action-scripts.git action-scripts && mv action-scripts/* .
      - name: Run CVE Check for Packages
        shell: bash
        run: bash packages-cve-check.sh && cat cve-report.json
      - name: Upload CVE Check for Packages Report
        uses: actions/upload-artifact@v4
        with:
          name: cve-report
          path: cve-report.json
