name: SOUP - CVE Check
on:
  workflow_call:
    inputs:
      type:
        description: 'Type of package manager'
        required: true
        type: string
      package:
        description: 'Name of the package'
        required: true
        type: string
      version: 
        description: 'Version of the package to include'
        required: true
        type: string

jobs:
  check-cves:
    env:
      GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
    runs-on: [self-hosted, Linux]
    steps:
      - uses: QuickBirdEng/actions/checkout-ssh@main
        with:
          ssh-private-key: ${{ secrets.CI_SSH_PRIVATE_KEY_FOR_GITHUB_PRIVATE_REPOS }}
      - name: Check CVE
        uses: QuickBirdEng/actions/soup-cve-check@main
        with:
          type: ${{ inputs.type }}
          package: ${{ inputs.package }}
          version: ${{ inputs.version }}
