on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node version'
        required: true
        type: string
      modules:
        description: 'Modules to check'
        required: true
        type: string
      reports-dir:
        description: 'Reports directory'
        required: false
        type: string
        default: reports

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web:
    runs-on: [ self-hosted, node ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Web Vulnerability and Outdated Packages Report
        uses: QuickBirdEng/actions/web-vulnerability-and-outdated-packages-report@web-dependency-reports
        with:
          modules: ${{ inputs.modules }}
          node-version: ${{ inputs.node-version }}
